######################################################################
# Automatically generated by qmake (2.01a) vie feb 24 14:16:27 2012
######################################################################

QT += xml xmlpatterns sql

CONFIG += qtestlib
TEMPLATE = app
TARGET = test
DEPENDPATH += . tests
INCLUDEPATH += .

# Input
HEADERS += CamDistortion.h \
           Camera.h \
           CameraModel.h \
           CameraModelReader.h \
           Decentering.h \
           DistortionModel.h \
           libPW.h \
           libPW_global.h \
           PhotogrammetricModel.h \
           RadialBasic.h \
           RadialDistortion.h \
           RadialExtended.h \
           RTDistortion.h \
    tests/TestWaitForResultsProcess.h \
    tests/TestAperoDistReader.h \
    WaitForResultsProcess.h \
    PWImage.h \
    Project.h \
    Process.h \
    MultiProcess.h \
    ExternalProcess.h \
    tests/WaitForResultsClient.h \
    tests/TestMicMacEOReader.h \
    MicMac/MicMacEOReader.h \
    ExternalOrientation.h \
    tests/TestCalculateImagePoints.h \
    MicMac/AperoModelReader.h \
    PW2dPoint.h \
    PWPoint.h \
    PW3dPoint.h \
    PersistenceManager.h \
    tests/TestPersistenceManager.h
SOURCES += CamDistortion.cpp \
           Camera.cpp \
           CameraModel.cpp \
           CameraModelReader.cpp \
           Decentering.cpp \
           DistortionModel.cpp \
           libPW.cpp \
           PhotogrammetricModel.cpp \
           RadialBasic.cpp \
           RadialDistortion.cpp \
           RadialExtended.cpp \
           RTDistortion.cpp \
           tests/TestAperoDistReader.cpp \
    tests/TestWaitForResultsProcess.cpp \
    tests/TestsMain.cpp \
    WaitForResultsProcess.cpp \
    PWImage.cpp \
    Project.cpp \
    Process.cpp \
    MultiProcess.cpp \
    ExternalProcess.cpp \
    tests/WaitForResultsClient.cpp \
    tests/TestMicMacEOReader.cpp \
    MicMac/MicMacEOReader.cpp \
    ExternalOrientation.cpp \
    tests/TestCalculateImagePoints.cpp \
    MicMac/AperoModelReader.cpp \
    PW2dPoint.cpp \
    PWPoint.cpp \
    PW3dPoint.cpp \
    PersistenceManager.cpp \
    tests/TestPersistenceManager.cpp
RESOURCES += libPW.qrc
